
package client.stub;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserEndpoint", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserEndpoint {


    /**
     * 
     * @param user
     * @return
     *     returns client.stub.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.CreateUserResponse")
    @Action(input = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/createUserRequest", output = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/createUserResponse")
    public User createUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.DeleteUserResponse")
    @Action(input = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/deleteUserRequest", output = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/deleteUserResponse")
    public String deleteUser(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<client.stub.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUsers", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.ListUsers")
    @ResponseWrapper(localName = "listUsersResponse", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.ListUsersResponse")
    @Action(input = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/listUsersRequest", output = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/listUsersResponse")
    public List<User> listUsers();

    /**
     * 
     * @param arg1
     * @param id
     * @return
     *     returns client.stub.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.UpdateUserResponse")
    @Action(input = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/updateUserRequest", output = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/updateUserResponse")
    public User updateUser(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1);

    /**
     * 
     * @param id
     * @return
     *     returns client.stub.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://endpoint.soap_crud_server.java_ws_server/", className = "client.stub.GetUserByIdResponse")
    @Action(input = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/getUserByIdRequest", output = "http://endpoint.soap_crud_server.java_ws_server/UserEndpoint/getUserByIdResponse")
    public User getUserById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
